# Generated by Django 5.0.7 on 2026-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(choices=[('DV', 'Design Verification'), ('RTL', 'RTL Design'), ('FPGA', 'FPGA Prototyping'), ('UVM', 'UVM Testbench'), ('COVERAGE', 'Functional Coverage'), ('EMBEDDED', 'Embedded Systems'), ('CONSULTING', 'General Consulting')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='NEW', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
